version: '3.7'

services:
  db:
    image: couchbase:community-7.0.0
    container_name: couchbase_test_db
    restart: always
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - couchbase_data:/opt/couchbase/var

  backend:
    build: .
    container_name: couchbase_test_backend
    volumes:
      - ./src:/var/www/src
    ports:
      - 3000:3000
    depends_on:
      - db
    
volumes:
  couchbase_data: